# k8s/backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourism-backend
  labels:
    app: tourism-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tourism-backend
  template:
    metadata:
      labels:
        app: tourism-backend
    spec:
      containers:
        - name: spring-app
          image: weirung/spring:latest   # ← 換成你的映像 tag
          ports:
            - containerPort: 8080
          # env:
          #   - name: SPRING_PROFILES_ACTIVE     # 如有需要
          #     value: prod
          #   - name: SPRING_DATA_MONGODB_URI    # 例：mongodb://mongo:27017/tourism
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongo-uri-secret
          #         key: uri
          resources:               # 視需求可調
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
