# k8s/backend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tourism-backend
  labels:
    app: tourism-backend
spec:
  type: ClusterIP         # Kind 內部可以先用 ClusterIP；要暴露 NodePort/Ingr ess 再改
  selector:
    app: tourism-backend
  ports:
    - port: 80            # 給其他 Pod / Ingress 用
      targetPort: 8080    # Spring Boot containerPort
      protocol: TCP
