version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: pg-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pg-data:/var/lib/postgresql/data

  my-java-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update   # 開發生成表用
      SPRING_PROFILES_ACTIVE: local           # 自訂 local profile
  frontend:
    build:
      context: ../Tourism_Keelung_Frontend
      dockerfile: Dockerfile
    container_name: tourism-frontend
    ports:
      - "3000:3000"
    depends_on:
      - my-java-app
volumes:
  pg-data:
