# GCP Cloud SQL 配置（生產環境）
spring.datasource.url=jdbc:postgresql:///postgres?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=nth-fiber-459808-b5:asia-east1:mypg
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# 生產環境建議設定
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
