name: Build & Deploy to Cloud Run
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # 讓 Workload Identity Federation 能用
      contents: read
    steps:
      - uses: actions/checkout@v4

      # 1) 透過 OIDC 與 GCP 連線
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/123456/locations/global/workloadIdentityPools/github/providers/my-provider'
          service_account: 'github-ci@PROJECT_ID.iam.gserviceaccount.com'

      # 2) Build & Push
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: asia-east1-docker.pkg.dev/PROJECT_ID/my-repo/myapp:${{ github.sha }}
          push: true

      # 3) Deploy
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: myapp
          image: asia-east1-docker.pkg.dev/PROJECT_ID/my-repo/myapp:${{ github.sha }}
          region: asia-east1
